name: BDD Tests

on:
  push:
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Verificar estructura del proyecto
      run: |
        echo "Estructura del proyecto:"
        ls -la
        echo "Contenido de test/:"
        ls -la test/ || echo "Directorio test/ no encontrado"
        echo "Contenido de test/features/:"
        ls -la test/features/ || echo "Directorio test/features/ no encontrado"
        echo "Contenido de test/features/steps/:"
        ls -la test/features/steps/ || echo "Directorio test/features/steps/ no encontrado"
        echo "Contenido de src/:"
        ls -la src/ || echo "Directorio src/ no encontrado"

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Ejecutar tests BDD
      run: |
        behave test/features/ --format=pretty

    - name: Run BDD tests and generate HTML report
      run: |
        mkdir -p reports
        behave test/features/ -f behave_html_formatter:HTMLFormatter -o reports/report.html

    - name: Upload HTML test report
      uses: actions/upload-artifact@v4
      with:
        name: bdd-report
        path: reports/report.html
