name: Behave BDD Tests

on:
  push:
    branches: [ main, develop, feature_* ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  behave-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Behave
      run: |
        python -m pip install --upgrade pip
        cd backend
        pip install -r requirements.txt

    - name: Configure Django for Behave
      run: |
        cd backend
        export DJANGO_SETTINGS_MODULE=migraine_app.settings
        export PYTHONPATH=$PWD:$PYTHONPATH

    - name: Run Behave tests for all features
      run: |
        cd backend
        export DJANGO_SETTINGS_MODULE=migraine_app.settings
        export PYTHONPATH=$PWD:$PYTHONPATH
        echo "Running BDD tests with Behave..."
        
        # Ejecutar tests de evaluacion_diagnostico
        echo "🧠 Testing Evaluacion y Diagnostico features..."
        behave evaluacion_diagnostico/features/ --format pretty --no-capture --tags=~@skip --no-logcapture || echo "Tests completed with issues in evaluacion_diagnostico"
        
        # Ejecutar tests de agendamiento_citas
        echo "📅 Testing Agendamiento de Citas features..."
        behave agendamiento_citas/features/ --format pretty --no-capture --tags=~@skip --no-logcapture || echo "Tests completed with issues in agendamiento_citas"
        
        # Ejecutar tests de tratamiento
        echo "💊 Testing Tratamiento features..."
        behave tratamiento/features/ --format pretty --no-capture --tags=~@skip --no-logcapture || echo "Tests completed with issues in tratamiento"
        
        # Ejecutar tests de analiticas
        echo "📊 Testing Analiticas features..."
        behave analiticas/features/ --format pretty --no-capture --tags=~@skip --no-logcapture || echo "Tests completed with issues in analiticas"

    - name: Generate Behave HTML Report
      if: always()
      run: |
        cd backend
        export DJANGO_SETTINGS_MODULE=migraine_app.settings
        export PYTHONPATH=$PWD:$PYTHONPATH
        mkdir -p reports
        behave evaluacion_diagnostico/features/ agendamiento_citas/features/ tratamiento/features/ analiticas/features/ \
          --format html --outfile reports/behave-report.html --tags=~@skip --no-logcapture || echo "Report generation completed with warnings"

    - name: Upload Behave Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: behave-reports
        path: backend/reports/
        retention-days: 30

    - name: Generate Test Summary
      if: always()
      run: |
        cd backend
        echo "## 🧪 Behave BDD Test Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Features Tested:" >> $GITHUB_STEP_SUMMARY
        echo "- 🧠 Evaluación y Diagnóstico" >> $GITHUB_STEP_SUMMARY
        echo "- 📅 Agendamiento de Citas" >> $GITHUB_STEP_SUMMARY
        echo "- 💊 Tratamiento" >> $GITHUB_STEP_SUMMARY
        echo "- 📊 Analíticas" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Archivos de Features:" >> $GITHUB_STEP_SUMMARY
        find . -name "*.feature" | sort >> $GITHUB_STEP_SUMMARY
